---
- name: user module demo
  hosts: localhost
  become: true
  tasks:
    - name: adduser in system
      ansible.builtin.user:
        name: ubuy
        password: "{{ '$6$hMzD8fm2Y6Cl4Qag$MgfVOGrzeHOKbY./VDKx1JoDAqkLiIXpVKTxZPdFhX5DRv0Df30xp8Uc030E/MBiGgh813N8nY3VsxQivGzOa/' | password_hash('sha512', 'mysecretsalt') }}"
        state: "present"
        shell: "/bin/bash"
        system: false
        create_home: true
        home: "/home/ubuy"
        comment: "Ansible ubuy"
        generate_ssh_key: true
